print("1.---------------------------------------")
print("Estamos en Febrero")
print("Seguimos estando en Febrero")
print(1,2,3,4,5,6,7,8,9,0,sep='==')
print(1,2,3,4,5,6,7,8,9,0)
print(1,2,3,4,5,6,7,8,9,0,sep='==',end='||')
print("2.---------------------------------------")
print("Dime tu nombre ? ")
nombre = input()
print("Cómo estás,",nombre,"?")
print("3.---------------------------------------")
edad = input("Cuántos años tienes? : ")
print("OK, tienes ", edad, " añazos!!")
print("4.---------------------------------------")
print("5.---------------------------------------")
print("6.---------------------------------------")
